### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by l4nce0** [ExplodingLemur/presentations#2]
Actually there has been a lot of talk about how to do this on the Facebook laser cutter group. It's got to the point where people were offering others equipment as a bounty to whoever would make a video, showing step by step how to put this together. So its not just me that is a tad confused. Hobbyists not professionals.

I mean you have it all there, and we appreciate all the work.. but we are hobbyists, and need a bit more hand holding. We want to be real sure we are writing it right. It would at least be helpful if the wire diagram showed the man in the middle board, instead of written instructions.. High rez photos as well would be good.

In regards to the video, that is not what I am talking about. That just shows it works. We need instructions, step by step, even just going over how its wired is helpful. The video shows it works but not how to do it.

**Comment by ExplodingLemur** [comment]
Ah, got it, this is regarding the K40 article, it wasn't clear (I have a presentation I gave in the repository, and some wiki articles on various topics). I'm afraid I don't really have the time to do a complete walkthrough video of every step. I didn't write it as a hand-holding guide, but to try to consolidate the information I found to get my own laser working (I'm just a hobbyist as well, and this was my first CNC machine of any kind).
